spring.application.name=weather-web-api

weather.provider=${WEATHER_PROVIDER:openweather}
weather.api-key=${OPENWEATHER_API:not_available}
weather.api-url=${BASE_URL:https://api.openweathermap.org/data/2.5}
weather.cache-ttl-minutes=${CACHE_TTL:10}

ratelimit.enabled=${RL_IS_ENABLED:true}
ratelimit.consumed-tokens=${BUCKET_CONSUME_TOKEN:1}
ratelimit.pattern=${PATTERN:/weather/*}
ratelimit.duration=${MINUTES_BETWEEN_REFILL:1}
ratelimit.number-of-tokens=${NUMBER_OF_REFILL_TOKENS:10}
ratelimit.cache-type=${CACHETYPE:REDIS}
ratelimit.daily-limit=${THIRD_PARTY_LIMIT:3}
ratelimit.redis-host=${SPRING_DATA_REDIS_HOST:localhost}
ratelimit.redis-port=${SPRING_DATA_REDIS_PORT:6379}
ratelimit.cache-TTL=${CACHE_TTL:30}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}

# The port Redis is listening on (6379 is the default)
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

